version: "3.8"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_LOGGING: true
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: aws-ecs-fargate-nodejs-todo-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      NODE_ENV: development
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
